language: java
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
before_deploy:
  - git config --local user.name "HyperiumDeploy"
  - git config --local user.email "hyperiumclient@gmail.com"
  - git tag -d $TRAVIS_BUILD_NUMBER
deploy:
  provider: releases
  api_key:
    secure: $GIT_SECURE
  file_glob: true
  file: build/libs/*
  on:
    repo: HyperiumClient/Hyperium

